name: Docker Artifacts

on:
  push:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: ship-to-datadog

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2

#       - name: Run tests
#         run: |
#           if [ -f docker-compose.test.yml ]; then
#             docker-compose --file docker-compose.test.yml build
#             docker-compose --file docker-compose.test.yml run sut
#           else
#             docker build . --file Dockerfile
#           fi

  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # Ensure test job passes before pushing image.
#     needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - name: Build image api-endpoint
        working-directory: api-endpoint
        run: docker build . --tag api-endpoint

      - name: Build image control-app
        working-directory: control-app
        run: docker build . --tag control-app

      - name: Build image kubernetes-webhook
        working-directory: kubernetes-webhook
        run: docker build . --tag kubernetes-webhook
